### ISSUE TITLE
Input can't be opened

### ISSUE THREAD

**Issue by Pacutacatete100** [pystardust/ani-cli#142] opened 2021-11-23 06:55 UTC
Whenever I try to watch an episode using this CLI, I get an error from VLC saying "Your input can't be opened: VLC is unable to open the MRL ".  I've already tried resetting VLC preferences, reinstalling, and turning windows firewall off and nothing seems to be working. 
![screenshot of error](https://user-images.githubusercontent.com/35910179/142981925-c5e5058e-c11c-409a-a3f3-b429ccca5333.PNG)

**Comment by joshualagat** [comment] 2021-11-23 07:51
Try Dink4n's fix on #139

**Comment by Pacutacatete100** [comment] 2021-11-23 08:10
Unfortunately, that did not work :(

**Comment by Dink4n** [comment] 2021-11-23 10:45
Possible duplicate of #134

**Comment by ura43** [comment] 2021-12-29 13:08
Probably duplicate of #134 
Closing

**Closed by ura43** 2021-12-29 13:08 UTC
Labels: type: support, os: windows, category: player
