### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by leytrha** [pystardust/ani-cli#136] opened 2021-11-20 07:09 UTC
Whenever I try watching an anime, it reaches the "Currently playing ..." screen, but mpv does not open (unlike last week, when ani-cli was working great).

**Comment by Dink4n** [comment] 2021-11-20 10:59
Possible duplicate of #135

**Comment by cirru05** [comment] 2021-11-20 17:03
Same issue here. If I want to download it prints the "Downloading episode <episode number>" and link which starts with "loadfast1.com", and it is an .m3u8 playlist, but after that it says, that "Download failed episode: <episode number>". When I try to ping the link it printed or the website it does not respond, and when I try to reach it trough browser the website says that the access is denied and it says that the website is trying to protect itself from online attacks (maybe it thinks that I am packet spamming/DoS-ing it?). The error code that the website gives is 1020. 
But it may be a problem because I am on 10.13.6 High Sierra. And yes, I have the right version of mpv, it's not an mpv problem.

**Comment by damky** [comment] 2021-11-20 19:53
not working for me either. I've been trying it with mpv and vlc.

**Comment by Shulkk** [comment] 2021-11-21 22:22
Maybe your ISP is blocking GoGo? Or it could just be that you're using an old version of ani-cli with the old gogoanime domain

**Comment by BluPenDragon** [comment] 2021-11-22 03:04
was working just fine, restarted my PC to apply updates and its no longer working, the terminal side works but no mpv window comes up,

**Comment by theqwardel** [comment] 2021-11-22 04:12
same thing, after rebooting pc its just stopped working

**Comment by Reaper176** [comment] 2021-11-22 15:46
Same for me after a reboot. Going through old issues now. I will update if I find a cause/fix.

**Comment by joshualagat** [comment] 2021-11-22 16:03
Tried seeing if it could open in VLC but after waiting for a bit, it doesn't work either. Same issue for me.

**Comment by Dink4n** [comment] 2021-11-22 16:04
Take a look at #139

**Comment by Reaper176** [comment] 2021-11-22 16:11
dink4n is correct. that is in fact the fix.

**Comment by cirru05** [comment] 2021-11-22 16:22
Those 2 lines fixed it, thx!

**Closed** 2021-12-19 09:09 UTC
