### ISSUE TITLE
Episodes not released yet bug

### ISSUE THREAD

**Issue by BenTowali** [pystardust/ani-cli#961] opened 2022-12-29 07:16 UTC
**Metadata**
Version: 3.4.0
OS: Arch Linux
Shell: zsh
Anime: any

**Describe the bug**
When I select any anime from my search it says "Episodes not released yet!"

**Steps To Reproduce**
1. Run `ani-cli`
2. Search for an anime and select the anime
3. Error

**Expected behavior**
I should be able to select an episode

**Screenshots**
![image](https://user-images.githubusercontent.com/108379869/209916951-9b436b8f-7fdc-4720-a58a-937724d8bb60.png)

**Comment by elliottophellia** [comment] 2022-12-29 07:22
animixplay dead so ani-cli too, you should check V4 branche bro

**Comment by 71zenith** [comment] 2022-12-29 07:32
duplicate of https://github.com/pystardust/ani-cli/issues/948

**Closed by 71zenith** 2022-12-29 07:32 UTC
Labels: type: bug, priority 2: medium
