### ISSUE TITLE
Normal quality and other quality doesn't work [Unusable!]

### ISSUE THREAD

**Issue by rbjnazz** [pystardust/ani-cli#337] opened 2022-01-14 12:38 UTC
test on _Aot_ and _Komi-san wa, Comyushou desu_

**Test 1**
```
Getting data for episode 1
720 quality doesn't exist, falling back to normal quality

Video URL not found
```

**Test 2**
```
Getting data for episode 1
480 quality doesn't exist, falling back to normal quality

Video URL not found
```

**Test 3**
```
Getting data for episode 1
360 quality doesn't exist, falling back to normal quality

Video URL not found
```

**Test 4**
```
Getting data for episode 1
normal quality doesn't exist, falling back to normal quality

Video URL not found
```

**Comment by ura43** [comment] 2022-01-14 14:11
This is probably the best Issue I've seen so far.
You tell me the problem, give a good Issue title, give two anime to reproduce and copy paste the corresponding terminal output.
This is an indirect duplicate of #217, but I will leave this open for now as I imagine you're not the only one experiencing this breakage and #217 is terribly titled

**Comment by Waa11a** [comment] 2022-01-14 16:10
Same!!

**Comment by JungerBoyo** [comment] 2022-01-14 16:18
Same here

**Comment by epeuu** [comment] 2022-01-14 19:19
I got issue like @rbjnazz
![Screenshot from 2022-01-14 20-17-21](https://user-images.githubusercontent.com/86723533/149572660-0655d166-5715-4731-9ef0-11ad316f386f.png)

**Comment by Seba244c** [comment] 2022-01-14 19:34
It seems that gogoanime.cm is down. That's probably why this isn't working.

![Screenshot_20220114_203129](https://user-images.githubusercontent.com/23051740/149574618-34e34abf-08ee-46d4-9ab5-dc8db8564e68.png)

**Closed** 2022-01-14 19:46 UTC
Labels: category: url, type: duplicate
