### ISSUE TITLE
Specific series not working but everything else does???

### ISSUE THREAD

**Issue by DevKn1ght** [pystardust/ani-cli#207] opened 2021-12-22 19:06 UTC
I've been using Ani-Cli for about a month now. But recently I had to reinstall Linux (PopOS!) as I've now done a full switch away from Windows. I've reinstalled the script and got MPV working with it.

Although everything worked when I watched One Piece a while ago, but now it just doesn't boot up anything once I select an episode? It does confirm currently playing the episode, but nothing shows up.

Literally any other series work with no issues, just One Piece. What's up with that?

**Comment by ARiceCake** [comment] 2021-12-22 23:34
Logged in to this long dormant account and came here to make basically the exact same comment, as I am having the same issue (in my case on a manjaro install). Very odd as One Piece is working just fine on the site this script scrapes from, and the script doesn't return any error about anything going wrong, simply nothing happens.

**Comment by Dink4n** [comment] 2021-12-23 03:40
Possible duplicate of #202

**Comment by ARiceCake** [comment] 2021-12-23 04:09
I did realise it was a possible dupe after I'd closed out the thread, I tried to fix suggest to line 129 from #202  but it spat out an error of 'unexpected end of program line 446' while the program was 445 lines long(or something to that effect, I've reinstalled and left vanilla for now but could recreate if the need be), though I did see that get a positive reaction in that particular thread so I may have a separate issue 

not experienced with the etiquette here so if I should go and repost this in #202 I certainly can

**Closed** 2021-12-29 12:09 UTC
Labels: os: linux, type: duplicate, category: parsing
