### ISSUE TITLE
Some episodes do not open at all, some play laggy

### ISSUE THREAD

**Issue by elcorito** [pystardust/ani-cli#194] opened 2021-12-13 02:49 UTC
I just recently downloaded ani-cli, and right off the bat I had an error, fixed it easily by installing mpv. Now there are very limited episodes from limited animes which actually play, and when they do there's a high percent chance that it will lag, a lot, to the point that I'm better off watching it on my browser.

I checked out previous problems, everything seems to be up to date, it does not seem to be the -f flag on setsid, I have installed all required dependencies...

The program works correctly, it displays that it is getting the data for the episode and displays other options, but still does not open the episode. 

Also I'm using Kali Linux.

Thanks for any help.

Disclaimer: I'm new as fuck to Linux, and even more to Github, not oblivious but I am still learning.
![Screenshot_2021-12-13_02-33-36](https://user-images.githubusercontent.com/96032388/145744468-84d24e9b-ba9f-4883-a212-50f5454f921e.png)

**Comment by MxSpoon** [comment] 2021-12-13 20:11
I have encountered this with both mint and manjaro

**Comment by sys128** [comment] 2021-12-13 23:52
Encountering something like this as well. It buffers a lot, if that's what you mean by "it's very laggy." The buffering is painful, even after checking my WiFi.

**Comment by elcorito** [comment] 2021-12-13 23:54
@sys128 I mean my wifi is not the best but it's more than enough for anime :/

**Comment by elcorito** [comment] 2021-12-13 23:55
@MxSpoon I suspect it has something to do with the compatibility of the distros, I will try It on Ubuntu and see what happens.

**Comment by sys128** [comment] 2021-12-14 00:01
I am on Linux Mint 20.1, an Ubuntu-based distro if that helps.

**Comment by elcorito** [comment] 2021-12-14 00:08
@Dink4n  What distro do you use?

**Comment by haaarp** [comment] 2021-12-14 22:17
Same problem here on Arch.

**Comment by Dink4n** [comment] 2021-12-15 03:55
> @Dink4n What distro do you use?

I Use Arch BTW

Possible duplicate of #192

**Comment by ura43** [comment] 2021-12-29 12:38
Could very well be a duplicate.
@elcorito please reopen with further info if you believe its not

**Closed by ura43** 2021-12-29 12:38 UTC
Labels: os: linux, status: needs more info, type: duplicate, category: parsing
