### ISSUE TITLE
No results found!

### ISSUE THREAD

**Issue by ultiMEIGHT** [pystardust/ani-cli#1057] opened 2023-03-12 13:59 UTC
I get a "No results found!" message after searching for anything. I have installed it from the source and made sure that I am on the latest version. I also tried installing via yay, but no success there too.

**Comment by finem4n** [comment] 2023-03-12 14:03
I just open ani-cli, updated it to 4.1.4 and also got "No results found"

**Comment by 71zenith** [comment] 2023-03-12 14:03
Duplicate of #1050 
Please read other issues before opening your own

**Closed by 71zenith** 2023-03-12 14:03 UTC
