### ISSUE TITLE
iina is crashing while opening any episode

### ISSUE THREAD

**Issue by mja0342** [pystardust/ani-cli#1418] opened 2024-09-12 19:25 UTC
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
Version: 4.9.0
OS: MacOS 14.6.1
Shell: zsh

**Describe the bug**
I upgraded my ani-cli version from 4.8 to 4.9.0 right after that, the Iina player is crashing while opening any episode of any anime.

**Steps To Reproduce**
1. Run `ani-cli`
2. bleach 
3. Choose Episode 1

**Expected behavior**
It needs to run the episode

**Screenshots (if applicable; you can just drag the image onto github. remove the following line if not needed)**
<img width="1674" alt="image" src="https://github.com/user-attachments/assets/ec06ebd9-81c3-442a-830a-b2c1ddd279d0">

**Comment by coderzawad** [comment] 2024-09-25 06:44
Maybe re install it and also u can restart your computer.

and if it doesnt works try freeing out ur mac's ram and then run

**Comment by port19x** [comment] 2024-10-17 06:57
Closing since noone can reproduce this

**Closed by port19x** 2024-10-17 06:57 UTC
Labels: type: bug, os: mac, category: player, priority 2: medium, status: can't reproduce

**Comment by mja0342** [comment] 2024-10-17 13:48
yes please do that I was able to fix that issue after removing both ani-cli and iina.
