### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by createvi** [pystardust/ani-cli#647] opened 2022-04-15 03:43 UTC
**Metadata (please complete the following information)**
Version: 2.0.3
OS: Kali Linux
Shell: zsh
Anime: All anime

**Describe the bug**
Not able to play any anime whenever i use `ani-cli -v anime` and select it it says 
`base64: invalid input
bad decrypt
140488617129344:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:../crypto/evp/evp_enc.c:599:
Video URL not found`
 
 i updated ani-cli using `sudo ani-cli -U`

**Steps To Reproduce**

1. Run `ani-cli -v anyanime`
2. Choose anything
3. Choose any episode

**Expected behavior**
I should be able to watch anime

**Comment by iamchokerman** [comment] 2022-04-15 04:29
duplicate of #646, hence closing it

**Closed by iamchokerman** 2022-04-15 04:29 UTC
Labels: type: bug, type: duplicate, priority 2: medium
