### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by MrKoshens** [pystardust/ani-cli#962] opened 2022-12-29 10:40 UTC
**Metadata (please complete the following information)**
Version: 3.4.7
OS: Arch Linux 
Kernel version: 5.15.85-1-lts
Shell: bash
Anime: konosuba, demon-slayer, rise of shield hero, etc

**Describe the bug**
It says "episodes not released yet". I am trying to watch some anime but it shows this error.

**Steps To Reproduce**

1. Run `ani-cli -q 480 `
2. type (demon slayer)
3. Choose 3

**Expected behavior**
It should show episodes/ number of episodes after I choose which season to watch.

**Screenshots (if applicable; you can drag the image onto GitHub)**

![2022-12-29_16-10](https://user-images.githubusercontent.com/74851124/209939832-b0399688-054b-414e-9ac5-abc6f0e87e7e.jpg)

**Additional context**

**Comment by justchokingaround** [comment] 2022-12-29 10:42
duplicate of #948

**Closed** 2022-12-30 05:55 UTC
Labels: type: bug, priority 2: medium
