### ISSUE TITLE
Episode 1/0 error

### ISSUE THREAD

**Issue by Austinrocket** [pystardust/ani-cli#152] opened 2021-11-29 03:34 UTC
Some anime that are just a single episode show as:
"Choose episode [1-0]:"
Choosing 1 says it's out of bounds and choosing 0 opens the player but cannot resolve the URL

The most popular example I could find would be with the newest BnHA movie:
"$ ani-cli
Search Anime: my hero
[1] maoyuu-maou-yuusha
...
[11] boku-no-hero-academia-the-movie-3
...
[20] boku-no-hero-academia-the-movie-2-heroesrising-dub
Enter number: 11
Choose episode [1-0]: 0
Episode out of range
Choose episode [1-0]: 1
Getting data for episode 1

Currently playing boku-no-hero-academia-the-movie-3 episode 0/0
[n] next episode
[p] previous episode
[s] select episode
[r] replay current episode
[q] exit
Enter choice: q"

Not sure what could resolve this issue atm, just wanted to report it.

Thanks!

**Comment by Reaper176** [comment] 2021-11-29 03:37
i am also doing the boku no hero. small world. same issue.

**Comment by Austinrocket** [comment] 2021-11-29 03:43
Yeah very strange. Must be some weird indexing issue...

**Comment by TheGlockMisc** [comment] 2021-11-29 05:40
Possibly a redirection issue while scraping? (IDK if it affects lol) gogoanime points the domain with "www1" subdomain recently.

**Comment by TheGlockMisc** [comment] 2021-11-29 05:51
I checked it.. and yeah, the episode/movie is not released yet..
i think they must fix this or they write a script that check if Episode exist or the Series/Movie does have episode or not.

**Comment by Austinrocket** [comment] 2021-11-29 05:53
Ohh I see, there is a listing for it but no actual content to pull... We should be checking to see if the content exists or not for sure. Thanks for the insight.

**Comment by Derisis13** [comment] 2021-11-29 08:38
This is an error caused by gogoanime changing their domain from `www.` to `www1.`, and the fix is out. Do a `git pull`, then `make uninstall && make install` to upgrade.

**Comment by ura43** [comment] 2022-01-01 18:34
Can confirm this is still an issue

**Comment by ura43** [comment] 2022-01-01 18:47
@RaynardGerraldo can you take a look?

**Comment by RaynardGerraldo** [comment] 2022-01-01 18:51
> @RaynardGerraldo can you take a look?

Sure,ill take a look at it later,can you specify the animes that are still outputting this problem? Because i saw this issue couple of days ago and tried the boku no hero movie and it worked

**Comment by ura43** [comment] 2022-01-01 19:38
Can you recheck?
Didn't work for me

**Comment by RaynardGerraldo** [comment] 2022-01-01 19:58
> Can you recheck? Didn't work for me
 
yep, boku-no-hero-academia-the-movie-2-heroesrising-dub works, but boku-no-hero-academia-the-movie-3 still doesnt work,and the only reason why it doesnt work is because no episode has been released in gogoanime, status ongoing https://www2.gogoanime.cm/category/boku-no-hero-academia-the-movie-3

**Comment by RaynardGerraldo** [comment] 2022-01-01 21:46
> Can you recheck? Didn't work for me

since this is a problem that can only be solved until gogoanime actually uploads something, i just added check if theres no episode then output error message, did this on my end,should i do a pr?

**Comment by ura43** [comment] 2022-01-01 21:49
Sounds good, it gives an error message for that movie?
Best we can do

**Comment by RaynardGerraldo** [comment] 2022-01-01 21:53
> Sounds good, it gives an error message for that movie?
> Best we can do

Yep,just made a pr you can test out the commit

**Closed** 2022-01-02 09:27 UTC
Labels: type: bug, category: parsing, priority 2: medium
