### ISSUE TITLE
download broken due to m3u8 aria2 incompatibility

### ISSUE THREAD

**Issue by rbjnazz** [pystardust/ani-cli#588] opened 2022-03-17 05:57 UTC
Version: 1.9.0
OS: Linux Mint 20.2
Shell: zsh
Anime: aot

Bug: Downloading is broken.

**Steps To Reproduce**
```bash
ani-cli -d "attack on titan final season part 2"
[1] shingeki-no-kyojin-the-final-season-part-2
[2] shingeki-no-kyojin-the-final-season-part-2-dub
[q] exit
Enter choice: 1
Range of episodes can be specified: start_number end_number 
Choose episode[1-10]: 1 10
```
this will loop 1 through 10
```bash
Getting data for episode 10 
Downloading episode 10 ... 

03/17 13:46:32 [NOTICE] Downloading 1 item(s)

03/17 13:46:33 [NOTICE] Download complete: ./shingeki-no-kyojin-the-final-season-part-2-010.mp4
Downloaded episode: 010 
```
then I got this
```bash
ls -l --size
.rw-rw-r-- linuxmint 414 B Mar 17 22 01:45 PM shingeki-no-kyojin-the-final-season-part-2-001.mp4
.rw-rw-r-- linuxmint 414 B Mar 17 22 01:45 PM shingeki-no-kyojin-the-final-season-part-2-002.mp4
.rw-rw-r-- linuxmint 414 B Mar 17 22 01:46 PM shingeki-no-kyojin-the-final-season-part-2-003.mp4
.rw-rw-r-- linuxmint 414 B Mar 17 22 01:46 PM shingeki-no-kyojin-the-final-season-part-2-004.mp4
.rw-rw-r-- linuxmint 414 B Mar 17 22 01:46 PM shingeki-no-kyojin-the-final-season-part-2-005.mp4
.rw-rw-r-- linuxmint 414 B Mar 17 22 01:46 PM shingeki-no-kyojin-the-final-season-part-2-006.mp4
.rw-rw-r-- linuxmint 414 B Mar 17 22 01:46 PM shingeki-no-kyojin-the-final-season-part-2-007.mp4
.rw-rw-r-- linuxmint 414 B Mar 17 22 01:46 PM shingeki-no-kyojin-the-final-season-part-2-008.mp4
.rw-rw-r-- linuxmint 413 B Mar 17 22 01:46 PM shingeki-no-kyojin-the-final-season-part-2-009.mp4
.rw-rw-r-- linuxmint 414 B Mar 17 22 01:46 PM shingeki-no-kyojin-the-final-season-part-2-010.mp4
```

**Comment by 71zenith** [comment] 2022-03-17 06:04
Update to the latest version. These are m3u8 links which aria2 can't download. v1.9.2 allows to download them with ffmpeg

**Comment by Quicksilver151** [comment] 2022-03-19 15:23
why does the m3u8 links always download the highest resolution no matter what resolution i select
would there be a way to fix that, or is that just a problem with it being m3u8

**Comment by CoolnsX** [comment] 2022-03-19 19:03
It's a problem with m3u8..

**Comment by CoolnsX** [comment] 2022-03-22 02:56
Fixed... U can update to latest version using ``ani-cli -U`` if u r using git version

**Comment by Derisis13** [comment] 2022-03-23 08:07
Not much activity here and the issue is solved. I'm closing it.

**Closed by Derisis13** 2022-03-23 08:07 UTC
Labels: type: bug, category: url, priority 2: medium
