### ISSUE TITLE
Episode list not showing up for any anime

### ISSUE THREAD

**Issue by Uchiha268** [pystardust/ani-cli#956] opened 2022-12-25 16:07 UTC
**Metadata (please complete the following information)**
Version: 3.4.7
OS: Mac OS 13.1
Shell: zsh 5.8.1
Anime: All anime

**Describe the bug**
The episode list not showing up.
Says episodes not released yet for every anime, check screenshot.

**Steps To Reproduce**

1. Run `./ani-cli`
2. Type in naruto

**Expected behavior**
Episode list should show up for naruto

**Screenshots (if applicable; you can just drag the image onto github)**
<img width="843" alt="image" src="https://user-images.githubusercontent.com/79242362/209474844-c4850f92-879c-4305-94b0-04f398af6261.png">

**Additional context**

**Comment by justchokingaround** [comment] 2022-12-25 16:10
duplicate of #948

**Closed** 2022-12-25 16:10 UTC
Labels: type: bug, priority 2: medium
