### ISSUE TITLE
Keep asking user for episode number when there's no valid episode [1-0]

### ISSUE THREAD

**Issue by mizuday** [pystardust/ani-cli#170] opened 2021-12-05 18:09 UTC
Anime: SWORD ART ONLINE: PROGRESSIVE MOVIE - HOSHI NAKI YORU NO ARIA
![image](https://user-images.githubusercontent.com/68516528/144758105-78ceab8e-e879-45cb-bebb-29b1f3aece2a.png)

**Comment by TheGlockMisc** [comment] 2021-12-05 23:31
Possible Duplicate of #152

**Comment by ura43** [comment] 2021-12-29 12:10
Closing in favor of #152

**Closed by ura43** 2021-12-29 12:10 UTC
Labels: type: duplicate
