### ISSUE TITLE
BNHA 5th Season Dub 8th Ep no link

### ISSUE THREAD

**Issue by DFireTech** [pystardust/ani-cli#877] opened 2022-08-30 01:37 UTC
**Metadata**
Version: 3.3
OS: [Ubuntu Server
Shell: bash
Anime: My Hero Academia 5th Season Dub

**Describe the bug**
Could not download episode 8, said "Could not find link" Ran -dx, link was not there for all three providers. Can manually grab from animix.

**Steps To Reproduce**

1. Run `ani-cli -d boku no hero academia 5th season dub`
2. Choose episode 8

**Expected behavior**
Downloading should work

**Comment by Derisis13** [comment] 2022-08-31 13:34
duplicate of #878

**Closed by Derisis13** 2022-08-31 13:34 UTC
Labels: type: bug, priority 2: medium

**Comment by DFireTech** [comment] 2022-09-06 00:41
This wasnt a dupe, im still having this issue despite ani-cli being able to download episodes otherwise.
