### ISSUE TITLE
Downloaded files are not working as intended.

### ISSUE THREAD

**Issue by mixalis1987** [pystardust/ani-cli#1111] opened 2023-05-08 01:56 UTC
**Metadata (please complete the following information)**
Version: [4.2.5]
OS: [Manjaro Linux XFCE]
Shell: [bash]
Anime: [Kimetsu no yaiba: Katanakaji no Sato-hen]

**Describe the bug**
Downloading is broken.
Downloads "kimetsu-no-yaiba-katanakaji-no-satohen-episode-5-sub.mp4" in less than a second and nothing can be played. Normal streaming is working fine with the exact same file name in mpv.

Downloaded files are far too small to be a video file. they are in Bytes.

**Steps To Reproduce**

1. Run `ani-cli -d kimetsu`
2. Choose 1
3. Choose episode 1-5

**Expected behavior**
Downloading should work

**Comment by port19x** [comment] 2023-05-08 09:13
this is a duplicate of #1108 
A fix is in the making in #1109

**Closed by port19x** 2023-05-08 09:13 UTC
Labels: type: bug, priority 2: medium
