### ISSUE TITLE
History can only hold 16 anime

### ISSUE THREAD

**Issue by kvkhh** [pystardust/ani-cli#606] opened 2022-03-31 12:56 UTC
**Metadata (please complete the following information)**
Version: 1.9.3
OS: Manjaro 21.2.5 Qonos
Shell: zsh 5.8.1
Anime: NA

**Describe the bug**
The history only holds space for 16 anime. When 17 anime is opened and watched, the history does not store the new anime.

**Steps To Reproduce**

1. Open 16 different anime  
2. ani-cli -c
3. View history
4. Open 17th anime
5. ani-cli -c
6. View history
7. Observe the 17th anime not being indexed

**Expected behavior**
item count greater than 16 anime should also be indexed

**Screenshots (if applicable)**
NA

**Additional context**

**Comment by Derisis13** [comment] 2022-03-31 15:11
Couldn't reproduce the bug, here's a screenshot with 17 animes displayed after using `ani-cli -c`:
![image](https://user-images.githubusercontent.com/66648475/161088635-422fc605-afa8-4bc3-bb9c-ef679354120c.png)
Aren't you on the last episode on any of the entries in your history? ani-cli only shows history entries where the next episode is available to play.

**Comment by ura43** [comment] 2022-04-05 12:11
Since v2 uses a new history file convention, there is a high likelyhood your issue has been fixed in the process.
Since we couldn't reproduce it anyway, I'm closing the issue, but feel free to reopen it if your issue persists in the latest version

**Closed by ura43** 2022-04-05 12:11 UTC
Labels: type: bug, priority 2: medium, category: ui ux, status: can't reproduce
