### ISSUE TITLE
No video playback in VLC (IOS)

### ISSUE THREAD

**Issue by Aloushii** [pystardust/ani-cli#1401] opened 2024-08-20 04:21 UTC
**Metadata (please complete the following information)**
Version: 4.8.11
OS: iOS
Shell: Alpine
Anime: Any

**Describe the bug**
When opening an episode in VLC the screen is black and the video doesn't load and closes immediately with "playback failed" notified on the screen. (View screenshot at the end)

**Expected behavior**
Playback should work
--

I tried uninstalling and reinstalling ani-cli and VLC but it did not solve the issue.
I tried with different animes and episodes too.

**screenshot**
![image](https://github.com/user-attachments/assets/fe323816-79db-4826-8804-19e9d407cd85)

**Comment by Lockl00p** [comment] 2024-08-23 01:37
Oh yikes, let me try to see what the problem is…

**Comment by Lockl00p** [comment] 2024-08-23 16:03
I found a fix. I’ve made a PR to get it merged.

**Closed** 2024-08-24 16:57 UTC
Labels: type: bug, os: other, category: player, priority 2: medium
