### ISSUE TITLE
Gogoanime url handling is broken

### ISSUE THREAD

**Issue by D0nnieD4rk0** [pystardust/ani-cli#221] opened 2021-12-27 18:03 UTC
its probably since they've got a new domain "gogoanime.wiki" instead of the old gogoanime.vc

**Comment by FatSquare** [comment] 2021-12-27 18:18
No, this is not the problem, you can change it.

```
nano /usr/bin/ani-cli
```

**Comment by helcone** [comment] 2021-12-27 18:27
I have the same issue I tried to edit the scripts and add the following to try to resolve it. 

```
# base_url="https://www1.gogoanime.cm"
# base_url="https://www1.gogoanime.wiki"
base_url="https://www2.gogoanime.cm"
```
None of these domains worked or open the mpv on ARCH as well

**Comment by NWJ9PB** [comment] 2021-12-28 02:37
Seems gogoanime changed something on the backend that handles the urls, look #217

**Comment by Anarchyserver** [comment] 2021-12-28 05:35
same here it shows the list but not opening mpv or even downloading anything. does anyone know if the windows version works

**Comment by VG08** [comment] 2021-12-28 08:05
I am on arch and it doesn't work for me anymore

**Comment by Anarchyserver** [comment] 2021-12-28 08:45
> I am on arch and it doesn't work for me anymore

I think it's a problem with gogoanime and not the os anyone is using.

**Comment by TheGlockMisc** [comment] 2021-12-28 09:23
> > I am on arch and it doesn't work for me anymore
> 
> I think it's a problem with gogoanime and not the os anyone is using.

Exactly.

**Comment by VG08** [comment] 2021-12-28 11:29
Ik it's prolly not the os but was just telling ( i didn't do it to flex arch)

**Comment by 1Light** [comment] 2021-12-28 12:26
the link that ani-cli try to play is the issue i think
for example this is for death note ep1 
i printed the link the ani-cli runs and tried it in terminal 

$ mpv https://gogoplay1.com/embedplus?id=MTA2MjQ=&token=KomJxMnGpzfYdsFUuorWoQ&expires=1640695796

ytdl_hook] ERROR: Unsupported URL: https://gogoplay1.com/embedplus?id=MTA2MjQ=&token=KomJxMnGpzfYdsFUuorWoQ&expires=1640695796 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 
Failed to recognize file format.

**Comment by Anarchyserver** [comment] 2021-12-28 13:19
> the link that ani-cli try to play is the issue i think for example this is for death note ep1 i printed the link the ani-cli runs and tried it in terminal
> 
> $ mpv https://gogoplay1.com/embedplus?id=MTA2MjQ=&token=KomJxMnGpzfYdsFUuorWoQ&expires=1640695796
> 
> ytdl_hook] ERROR: Unsupported URL: https://gogoplay1.com/embedplus?id=MTA2MjQ=&token=KomJxMnGpzfYdsFUuorWoQ&expires=1640695796 [ytdl_hook] youtube-dl failed: unexpected error ocurred Failed to recognize file format.
> 
> but the sub links on the download page works well with mpv https://gogoplay1.com/download?id=MTA2MjQ=&typesub=Gogoanime-SUB&title=Death+Note+Episode+1
> 
> eg $mpv https://lb.loadfast1.com/cdn5/92bd0b67e03416084ffd8bb811b736ff/EP.1.v0.1639176238.720p.mp4?mac=b2u7upX79YizsqMx8XZae9l51fRvL8Q7BjsN0bP7gKk%3D&expiry=1640701756040

correct me if im wrong but what ur trying to say is that gogoanime changed it so that the links that the tool connects to for playing anime are changed so the tool trying to connect to the old ones does not work

**Comment by Partha2003** [comment] 2021-12-28 14:33
> Ik it's prolly not the os but was just telling ( i didn't do it to flex arch)

I tried with a Ubuntu based OS and a Arch based OS and can confirm menu shows up but mpv doesn't start up.

**Comment by Partha2003** [comment] 2021-12-28 14:38
> I have the same issue I tried to edit the scripts and add the following to try to resolve it.
> 
> ```
> # base_url="https://www1.gogoanime.cm"
> # base_url="https://www1.gogoanime.wiki"
> base_url="https://www2.gogoanime.cm"
> ```
> 
> None of these domains worked or open the mpv on ARCH as well

Could you please also try these?

https://gogoanime.nl/home
https://gogoanime.nl

**Comment by CoolnsX** [comment] 2021-12-28 18:25
> I have the same issue I tried to edit the scripts and add the following to try to resolve it.
> 
> ```
> # base_url="https://www1.gogoanime.cm"
> # base_url="https://www1.gogoanime.wiki"
> base_url="https://www2.gogoanime.cm"
> ```
> 
> None of these domains worked or open the mpv on ARCH as well

It's https://gogoanime.wiki
And if that doesn't work.. maybe ur ISP is blocking it..

**Comment by Anarchyserver** [comment] 2021-12-28 20:01
> 
still nothing the downloads fail too, also the actual gogoanime site is not blocked for me so i doubt that its the case

**Comment by B3HOID** [comment] 2021-12-28 20:57
Could this perhaps be fixed by editing the `get_links () {` section of the script? 

> correct me if im wrong but what ur trying to say is that gogoanime changed it so that the links that the tool connects to for playing anime are changed so the tool trying to connect to the old ones does not work
In that case we have to find the source for the new m3u8 stream links

**Comment by Jan9103** [comment] 2021-12-28 21:05
yes the issues seems to be within get_links() (it returns nothing). ive added a bunch of printfs into it and it seems to stop executing after the curl command (which works if you run it manually) (im neither expierenced with posix nor this script) - the links are still there in a list, but when i tried to manually open them (with referrer) it dosnt work as well (maybe i ended up with a bad one, but i thought at least one of the 6 mirrors should still be up)

**Comment by RaynardGerraldo** [comment] 2021-12-28 21:38
#209 just made a temporary fix, feel free to test it out and identify the error

**Comment by Partha2003** [comment] 2021-12-29 03:33
> #209 just made a temporary fix, feel free to test it out and identify the error

The comment by Kungger-git?

**Comment by WubzyGD** [comment] 2021-12-29 04:52
Yup, searches just fine for me but doesn't end up opening mpv.

**Comment by RaynardGerraldo** [comment] 2021-12-29 04:54
> > #209 just made a temporary fix, feel free to test it out and identify the error
> 
> The comment by Kungger-git?

No,look at the commits

**Comment by ura43** [comment] 2021-12-29 11:53
#219

**Comment by ura43** [comment] 2021-12-29 12:04
There seem to be a lot of open issues boiling down to this same problem. 
If I mistakenly closed your issue and your confident your problem is not caused by gogoanime url parsing, please reopen it

**Comment by WubzyGD** [comment] 2021-12-29 12:08
@ura43 is there a fix or...

**Comment by sdaqo** [comment] 2021-12-29 12:15
> @ura43 is there a fix or...

As mentioned in my [comment](https://github.com/pystardust/ani-cli/issues/216#issuecomment-1001255516), gogoanime completely changed the way it works. My workaround in my [script](https://github.com/sdaqo/anipy-cli) is done with Selenium, a tool to automate browsing websites, it utilizes the webdriver from a browser of choice. There even is a [implementation for Bash](https://github.com/Rasukarusan/shellnium), so it can be fixed, if someone does it.

**Comment by WubzyGD** [comment] 2021-12-29 12:21
> > @ura43 is there a fix or...
> 
> As mentioned in my [comment](https://github.com/pystardust/ani-cli/issues/216#issuecomment-1001255516), gogoanime completely changed the way it works. My workaround in my [script](https://github.com/sdaqo/anipy-cli) is done with Selenium, a tool to automate browsing websites, it utilizes the webdriver from a browser of choice. There even is a [implementation for Bash](https://github.com/Rasukarusan/shellnium), so it can be fixed, if someone does it.

I shall install yours for now then, thank you

**Comment by Fmert24** [comment] 2021-12-29 13:13
> @ura43 is there a fix or...

https://github.com/pystardust/ani-cli/commit/5a0261126682295387977509066f8a6f0ead30f3

**Comment by ura43** [comment] 2021-12-29 13:19
Great to see such a high activity here.
This will probably be fixed sometime next week.
The problem right now is that we have 10 versions of the same issue open and probably 5 fixes that would fix all of them. 
Coordinating the right fix will be a challenge

**Comment by ura43** [comment] 2021-12-29 13:28
> > @ura43 is there a fix or...
> 
> As mentioned in my [comment](https://github.com/pystardust/ani-cli/issues/216#issuecomment-1001255516), gogoanime completely changed the way it works. My workaround in my [script](https://github.com/sdaqo/anipy-cli) is done with Selenium, a tool to automate browsing websites, it utilizes the webdriver from a browser of choice. There even is a [implementation for Bash](https://github.com/Rasukarusan/shellnium), so it can be fixed, if someone does it.

Do you think reffering our users to gogoanime clones is a viable solution? Implementing a workaround using a headless browser seems more involved than it should be, so this would be a last resort

**Comment by sdaqo** [comment] 2021-12-29 13:41
> Do you think reffering our users to gogoanime clones is a viable solution? Implementing a workaround using a headless browser seems more involved than it should be, so this would be a last resort

So I don't really know a lot of anime sites since I mainly torrent anime to watch them, but if finding a clone and implementing a script so that it works isn't a pain, it would be a viable solution to the problem.

**Comment by ura43** [comment] 2021-12-29 17:17
[PR 209](https://github.com/pystardust/ani-cli/pull/209) should solve this issue and #227 with it

**Comment by ura43** [comment] 2021-12-29 19:52
PR 209 didn't solve the issue for me. Tested on debian unstable, wanted to watch flcl progressive ep 1

**Closed** 2021-12-29 22:27 UTC
Labels: type: bug, help wanted, status: needs triage, category: url, Priority 1: high

**Comment by ura43** [comment] 2021-12-29 22:37
This should now be resolved. Tested playing one piece on debian unstable
