### ISSUE TITLE
Panel for next and previous not working

### ISSUE THREAD

**Issue by reconlx** [pystardust/ani-cli#1150] opened 2023-06-14 06:36 UTC
**Metadata (please complete the following information)**
Version: 4.4.3
OS: MacOS Ventura 
Shell: fish
Anime: Fighting Spirit (Hajime no Ippo)

**Describe the bug**
Choosing next or previous is the panel is broken, its just stuck here ⬇️ 
![panel](https://github.com/pystardust/ani-cli/assets/66986299/f72e85f7-2411-4bf4-aafd-b07a3f3e63db)

**Steps To Reproduce**

1. Run `ani-cli -d flcl`
2. Choose 2 (fooly-cooly)
3. Choose episode 1
4. Click on next episode

**Comment by justchokingaround** [comment] 2023-06-24 21:46
works fine on v `4.4.4` on mac os, when running `ani-cli fighting spirit`. try updating

**Comment by reconlx** [comment] 2023-07-05 15:42
![CleanShot 2023-07-05 at 23 42 21](https://github.com/pystardust/ani-cli/assets/66986299/7381f0c7-1d1b-4342-ba95-936862a18afd)

now i cant event watch naruto :(

**Comment by reconlx** [comment] 2023-07-05 15:43
version 4.4.5

**Comment by justchokingaround** [comment] 2023-07-05 15:47
duplicate of #1161

**Closed by justchokingaround** 2023-07-05 15:47 UTC
Labels: type: bug, os: mac, priority 2: medium, category: ui ux, status: can't reproduce
