### ISSUE TITLE
(v3.3.3) Video player doesn't open on specific episode, but no errors in terminal.

### ISSUE THREAD

**Issue by CubeyAlchemist** [pystardust/ani-cli#885] opened 2022-09-07 17:38 UTC
**Metadata (please complete the following information)**
Version: 3.3.3
OS: Linux Mint 20.2
Shell: dash
Anime: Bleach

**Describe the bug**
When attempting to play episode 140, no errors are reported in terminal, but the media player does not open and there appears to be no action being taken by the program.

**Steps To Reproduce**
1. Run `ani-cli bleach`
2. Select option matching "bleach dub" - usually (3)
3. Choose episode 140

**Expected behavior**
Media player should open automatically within a few seconds and auto-play the episode selected.

**Screenshots (if applicable; you can just drag the image onto github)**
Screenshot of terminal after running the above steps.
![bleach140bug](https://user-images.githubusercontent.com/8694934/188942940-98859eb2-2cf4-4368-ad98-363318b2a380.PNG)

**Additional context**
I have been binging Bleach the past week, and this is the first episode I have encountered that refused to play/open without an error.
I tested the next episode (141), which works perfectly fine. I haven't tested the other ~220 yet.
I checked the host site to see if the episode was up and available - which it is: https://animixplay.to/v1/bleach-dub/ep140

**Comment by port19x** [comment] 2022-09-08 06:36
Closing as duplicate of #884

**Closed by port19x** 2022-09-08 06:36 UTC
Labels: type: duplicate
