### ISSUE TITLE
Windows Version Not Working

### ISSUE THREAD

**Issue by Navknight** [pystardust/ani-cli#330] opened 2022-01-12 07:55 UTC
The windows version installed without any errors, but as soon as I played something, VLC would open and close within a second and the program gives me the options it does when an episode finishes

**Comment by Clest1** [comment] 2022-01-12 09:01
Same for me, I tried to check how the script work on my own, seem like the scraping method for the '$video_url' don't work and leave a empty string.
By so, If you have VLC in loop mode, it start read random local file, else it close immediatly.

Unfortunatly there is no windows maintainer at the moment : #320

**Comment by Fmert24** [comment] 2022-01-13 17:18
> Same for me, I tried to check how the script work on my own, seem like the scraping method for the '$video_url' don't work and leave a empty string. By so, If you have VLC in loop mode, it start read random local file, else it close immediatly.
> 
> Unfortunatly there is no windows maintainer at the moment : #320

If you are using win10 or win 11 you can use WSL  with X-Server and set up ani-cli in wsl

**Comment by ura43** [comment] 2022-01-14 12:13
I found someone willing to consider taking on maintenance of the windows branch.
Let's hope we can make the script more easy to install for you guys soon

**Comment by ura43** [comment] 2022-01-18 19:57
> > If you are using win10 or win 11 you can use WSL with X-Server and set up ani-cli in wsl
> 
> sound like a lot of pain, however I did find this recent guide, not using X-server but WSL 2 : https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps
> 
> Could be great, if gogoaninme didn't fixed the scrapping...

The scraping fix is backported to the windows branch now

**Comment by ura43** [comment] 2022-01-19 19:13
We may merge the branches again in the foreseeable future. Closing since you found a workaround

**Closed by ura43** 2022-01-19 19:13 UTC
Labels: type: support, os: windows

**Comment by Arctic-Circle-System** [comment] 2022-01-24 11:59
Isn't using WSL basically just installing a Linux distro that attaches to Windows? I wouldn't really consider the Windows port fixed if that's the only way it works on Windows. ~Opal

**Comment by ura43** [comment] 2022-01-24 12:15
> Isn't using WSL basically just installing a Linux distro that attaches to Windows? I wouldn't really consider the Windows port fixed if that's the only way it works on Windows. ~Opal

I 100% agree. The issue is that we have to somewhat reinvent the wheel when it comes to windows support since the windows-vlc branch is terribly out of date.
Me and CoolnsX are working on a fix, but we need testers. If you're down please join the discord
