### ISSUE TITLE
Serial Experiments Lain loading issues

### ISSUE THREAD

**Issue by neoserpent** [pystardust/ani-cli#517] opened 2022-02-08 15:18 UTC
Version: v1.7.0 (ani-cli-git r449.95605a7-1)
OS: Arch Linux
Shell: bash 5.1.16
Anime: Serial Experiments Lain

[Bug]

Can't watch any episode of Serial Experiments Lain.
For some reason, every time I try to watch any of that anime's episodes, MPV will quickly load them up to some point and will then load them really slowly or freeze the loading process altogether. For example, if I try to watch episode 1, MPV might only load the first 8 minutes (or maybe 7, or 9, as it really is pretty random) of the episode and then load the rest really slowly (or just stop loading it).

[Steps To Reproduce]

1. Run `ani-cli serial experiments lain`
2. Choose option 1 or 2
3. Choose any episode

[Expected behavior]

MPV should have no problems loading any episode

**Comment by Derisis13** [comment] 2022-02-08 17:09
I tried to reproduce, but it's playing fine for me. Occasional hiccups are however not unheard of, and are the nature of the site we're scraping (see disclaimer.md). We have no control over them, so your best guess is to try it again at a later time.

**Comment by neoserpent** [comment] 2022-02-08 17:47
> I tried to reproduce, but it's playing fine for me. Occasional hiccups are however not unheard of, and are the nature of the site we're scraping (see disclaimer.md). We have no control over them, so your best guess is to try it again at a later time.

I see, but, isn't it odd that I can watch it just fine on gogoanime? I really don't know much about this, but I'd suppose that if this really is a hiccup problem, I should be having the same issues on gogoanime, no? Also, I've tried to watch some other animes, and while there are some that play flawlessly, there are some others which have the same issues as Serial Experiments Lain, so this got me even more confused on what might be wrong. Maybe it has to do with MPV?

**Comment by ura43** [comment] 2022-02-08 19:14
Common duplicate of #360 
There is a workaround detailed there, try it out

**Closed by ura43** 2022-02-08 19:14 UTC
Labels: type: duplicate
