### ISSUE TITLE
Downloading doesn't work

### ISSUE THREAD

**Issue by FatahChan** [pystardust/ani-cli#451] opened 2022-01-29 04:23 UTC
**Metadata (please complete the following information)**
Version: 1.5.5
OS: [WSL (Ubuntu 20.04) on Windows 11
Shell: powershell/bash
Anime: all

**Describe the bug**
Downloading is broken.
 CUID#7 - Download aborted.
 
**Steps To Reproduce**

1. Run `ani-cli -d <any anime>`
2. Choose any number
3. Choose any episodes 

**Expected behavior**
Downloading should work

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/30260221/151647050-997b9172-19c0-4fbc-a8e8-68d218635c7c.png)

**Additional context**

**Comment by 71zenith** [comment] 2022-01-29 04:25
I can't reproduce the error

**Comment by FatahChan** [comment] 2022-01-29 04:29
@71zenith what additional information, that might help this case

**Comment by 71zenith** [comment] 2022-01-29 04:37
Does it repeat, or only one time

**Comment by FatahChan** [comment] 2022-01-29 04:52
happens every time with different anime as well, keep in mind Ii just updated ani-cli to the current version

**Comment by CoolnsX** [comment] 2022-01-29 08:04
It's the problem on your network... As it's working here..

**Comment by 71zenith** [comment] 2022-01-29 08:05
I was just thinking the same

**Comment by FatahChan** [comment] 2022-01-29 17:00
why streaming works but not downloading

**Comment by RaynardGerraldo** [comment] 2022-01-29 17:25
@FatahChan its working just fine for me, can you try and update the script and re run it?

**Comment by FatahChan** [comment] 2022-01-29 17:48
@RaynardGerraldo Thanks testing, seems result.

I am trying to install it on windows via git bash, I will report back once it is installed

**Comment by AlparslanAbdikoglu** [comment] 2022-01-30 00:35
HI I just did a reinstall with gitbash and its works :)

**Comment by FatahChan** [comment] 2022-01-31 15:10
@AlparslanAbdikoglu can you tell me how to install the dependencies on git bash, I was not able to install the dependencies

**Comment by ura43** [comment] 2022-02-01 06:06
Closing. The new install process through scoop should be easier

**Closed by ura43** 2022-02-01 06:06 UTC
Labels: type: support, os: windows, priority 3: low
