### ISSUE TITLE
"Episodes not released yet" for all any anime

### ISSUE THREAD

**Issue by parsivan** [pystardust/ani-cli#975] opened 2023-01-12 18:16 UTC
Version: 3.4.7
OS: Pop!_OS 22.04 LTS x86_64
Shell: bash 5.1.16
Anime: Any

Getting error message "Episode not released yet!" and i get this for any anime. I just installed ani-cli. I have all dependencies. i have installed through adding repository to apt and then apt install. i have done ani-cli -U to update.

**Steps To Reproduce**
i get this after searching for any anime and then selecting it. (the same with fzf)

**Expected behavior**
should give me the episode selector but i get the error.
![Screenshot from 2023-01-12 19-10-19](https://user-images.githubusercontent.com/21005543/212146185-8e0caea3-0298-4887-90d6-1c710ff025f7.png)

**Comment by 71zenith** [comment] 2023-01-12 18:19
duplicate of #948

**Closed by 71zenith** 2023-01-12 18:19 UTC
Labels: type: bug, priority 2: medium
