### ISSUE TITLE
Episode Choice Not Showing after Selecting Series

### ISSUE THREAD

**Issue by tjamalcodes** [pystardust/ani-cli#1075] opened 2023-03-29 22:35 UTC
**Metadata (please complete the following information)**
Version: 12.2
OS: MacOS
Shell: [zsh]
Anime: Natsume Yuujinchou, One Piece

**Describe the bug**
After selecting the anime title, it just goes back to the normal command line

**Steps To Reproduce**

1. Run `ani-cli  book of friends`
2. Choose 1 

**Expected behavior**
"Select Episode:"

**Screenshots (if applicable; you can just drag the image onto github)**
<img width="562" alt="image" src="https://user-images.githubusercontent.com/81659689/228682885-af5fe5c2-eaae-48c1-be85-1549cfbc0d60.png">
<img width="268" alt="image" src="https://user-images.githubusercontent.com/81659689/228682767-828f184e-ccfb-4968-9f0d-e53eadb80906.png">

**Comment by port19x** [comment] 2023-03-30 19:19
We have no idea how you got your hands on Version 12.2
Please share your wisdom dear time traveler :pray:

**Comment by justfoolingaround** [comment] 2023-04-03 05:49
D̷̼͝ȇ̶̗̠͖̲̗̮̇̎̊a̷̛̖͈̺͂͆̾̒ͅr̷͈͉̼̘̯͝ ̵̹̗̝͚̤͍́ų̸͙̜̯̟̬̊́s̷̡̠̫̘̋̏e̴̝̙͙̬̕͜r̶̝̥͍͍̩̿͊͘͜,̷͍̮̝͈̿͛̌̓̄͆ ̸̼̯̚̚͝y̶̡͖͙̥͇̫̽͗̌̕o̵̬͚̙͕̽̓̔́̊̽u̶̧̩͚̙͎̖̎'̵̱̤͇̅͌͝ṛ̸̲̞̗͛͘͜e̴͈̒̍̚͝ ̵̭͎̳͍̀̍̏̌͐̃u̶̲͈̍̐̓͠s̵̨͔̃̔̑̽i̴̗͛̂̅́̑͝n̵͎̟̩̒͂̓͠g̴̨̮͖̪̓̍̀̾͝͝ ̸͍̝̿̄͑`̶̫͎̘̃͂͋͜͜ḧ̷͉̩́͗̾̿͠t̸͈̣̟̭̖̓̂͛̂t̵̼͂̿͒͌̂̉p̸̠̜͇͓̍̔-̴̲̜͇̯͎͖͛t̵̘͉̘͇̤̲͋͗́į̵͇̄̆̾̈̕̕m̷̥̰̓̓͛̂́͜͠ȩ̶̢͇̤͇̝̓͠p̵̡̡͚̗̆̌̏̏ŕ̶̨̰͊̽̆͝o̵̖͇̎͐̓̅͑͜t̷͉͂̆̉́̎̕ǒ̴̭̜̞̿̌s̵͙̺̓:̷̫́̎̂̐͝͝/̶̨͖͎̜̺̥̾̔̈͛̓̚/̷͉̌͂̋̐2̶̢̛͉̬̖̙͛̏̇0̸̡͇̹̈́2̸̨̟̭̪̻̻̃3̷̣̰̎̔-̴͖̺̤͈͈̾̈́0̷̡̩͚̝̰̄3̵̼̺͉͈͛̆-̶̯̙̍̅̾3̶̻̝͇̿̔1̷̤͆̈́̒@̷͎͕̠͑̄ģ̷̛̘̽́͌͝͝i̶̡͖̬̱̼̲̅t̷̹̞̤̘͐́͑h̵̺̆̾ṷ̶̖̬̬̩͐̒̀͛b̸̜͚̘͖̄̈́̈́͛́ͅ.̸̧̠͚͚̿͆̂̌ͅć̸̛̙̈́́͒͝ő̸̢̓̋̎m̴̡̰͚̭͔̙̈/̸̻̗̇p̶̰̙̳̱̲̳͋̽ẏ̵̭̱͇̠̹̬͐ś̵̡̠͔̪̪͆̎̃̚ţ̶̤̜̜̔̔a̶̛͍̓̉͋̄̉r̷̭̦̈́̾͝d̶͇̮̝̠̾̊̐u̴͓̤̤̝͉̐͂͝͠s̷̖͙̗̦̾̊̒̂͂͊t̸̡͙̙̩͆̈̇̇̽͘/̵̨̘͚̮̼̕̕͜a̶̧̋̈́̉̂̿n̶̰͎͉͌̈́̿̈́̆͠i̴̛̺͇̤͑͊̃̚͜͝-̵̨̞͇͉̓̊͆č̸̻͕̉l̵̢̥̲̟͠i̴̻͇̅̒̈́́̃̉`̵̙͓̝̼̗̅́ ̷̛̖͈͇̖̥̫̀͑ỉ̶̛͉̈́̍̑͘ņ̷͕̘͓̀͑̈́̋ ̸͓̬̀͊͋p̶̖̠̟̰̘̄̈́͋̀r̴̨̠̬̲̤̊̆̂̓̅o̶̮̥̳̙̠̱̔̐͗ḓ̷̯͚͖͈̈́̀̀͗ͅu̴͎̖̽͑͑̈͠c̸̢̀͂̇̔t̶̫̠̻̟̋͋̒͋i̸͇̩͙̖̊̓̐ǫ̸̧̠̖̉n̷̤̅͊.̷͎͓̯̏̋ ̷̪̻̣͂̓͘A̸̢̳̤͕͗͛͐̎n̶̗̤̈͗y̶̮͂̿̚͜ ̶̢̦͎͍̗̺͆͌̊̑̐͠c̵̮̉̂̔h̶̩͖̬̭̗̃͋̚ą̴̛̟̖͈̄̈́n̸̆̈́͐̂͝ͅģ̴̱̰̫̟̂ē̶̗̱͖͉̦͑͗͒̾ş̵̺̇͝ ̷̨̲̜̬̾͆̋y̶͍̥̺̣̣̍̈ȱ̴͇͙͙̓̄̿̉ư̷̩͗̏̏̔͝ ̴̢̤͍̉m̶̠͉͙̻͒̾̊̒͒͝ͅa̶̘̟̦̙͊͆̓͛d̶̛͉̮̒̈e̸̢̢͙̤̯̪͋̐́͆̂ ̷͙̃̈́́̈́̄͂a̶̯̩͐̓̋r̸̺͚̪̥̖̀͆ͅé̷͔͌͝͝ ̵̧̛̠͕̮̼̖̇̀̈́̀̓n̵̬̲̬̾̚͘͠ǫ̸͙̩̹̜̔͗̄̋̐͋w̴̱̜͖̩͗̉̇̐ ̴̦͔̀p̵̠̦̾̅̓̉̕͠ë̵̈́ͅȑ̵̥̥̟̉̐̇m̴̫̬̖̩̓ą̵͚͚͖̞̽͋̋̎͜ṉ̶̕ë̷̥́̑n̷̝̩̘̏̊̓̓̂̑t̶̢̨͚̘͎̾́͂͊͠l̶̢̳̯̠̱͛͑̈́̒͋͛y̷̛͖͍͍͂̈́̃͝ ̸̥̠̹̪̘̬̂a̷͈̱͐̊ ̷̟̯̤͚́͗̓p̷̢̧̳̜̂̏a̴̡͇̠̫̲̥̒͒̏r̵̹̂̎t̶̢̘͈̺̞͒̓ ̴̘̩̀̆̈́o̴͇̝̬̣̍̆͝f̴̧̲̳̻͕̬̏͌̓̆̚ ̸̨̰̯͎̥̒͋͘h̷̢͚͍̣͗̀̑͜i̸̧͇̟̙̲̍͊͗̄̒̈́͜ṣ̵̢͓̞̖̎t̴̤͎̠͊̔o̸̭̞͖͊́r̸̛̰͔̰͗͗̐y̷̧̻͇̙̠͎̋̋̍̎̉͐.̶̭̊̽̂̈͝ ̷͎̥̿̊͗̔̚̚T̸͖̠̪̓h̷̞̬̐̓̊̈́͗é̶͎̪͓̝ ̵̡̙͚̥̯̤̕p̷͎̐̄̈͆o̴̡͓̍̓w̷͈̣̩̍͒͌e̷̢̧͔͕͔͍̍̓̇͗͝r̸̻̰͛s̶͇͎̹͍̟̊̈́̀̎ ̷̛̈͒̚ͅṯ̴̡̦͌͛̀͒̿ö̷͎͓̹͍́̓̂ ̷͎̪̭̼͍̦̒͑ṱ̷͈̦̙͋̈͠ŗ̴̨̥̳̀ą̵̘̹̺̙̀́̈́̉͝n̵̛̰̹̯͓̳̱͂̄̇͝͝ś̶̠̺͍̘͊̿̌̾͘c̸̯̜̝̱̜͋ȩ̴̬̦̀͒͘͜n̴̪̭̂̌͒͛d̴̥̦̖̊ ̵͓͛̍̂̊̌t̷̢̞̦̩̀̊ȋ̸̮̽̒͛̾̈m̴̝̻̹̝͌̚ͅe̷̛̺ ̵̯̰̄̈b̶̮̄͐͑̎e̴̙̼̤̝̭͆̿͊́̆́ļ̴̧̰̠̙͈̒̀̆̈́͝ō̵̢̦̙̜͔̜̄͌̈͝͠n̵̺̹̾̒́̑͜g̶̥̎̌͋͜ ̶̇͌̿̕͝ͅi̷̟̞͇̬̬͗͌̎̋͘n̸͉̦̺̤͕͌ ̸̱̐t̶͕̯̊͗͊̐h̷̟͂ȅ̶̼̗ ̴̮̟̜̲̰̒̑c̴̻͋e̸̺̙̍̐̉̋̾̚l̸̙͔͂̔̓͝͠ͅe̷̿ͅṡ̴̙̾́̒͝t̶͍̓̐̅͑̈́̕ḯ̵̛̲̐̎̿a̴̞̦̯͋͑̀̌͠͝l̷̨͖̃͠͝ ̴̡̦̪͉̙̰͒̈́r̷̨̲͆͐͒̀ë̷̟́̅̇̃a̶̢̻͋̄͐̆́̚l̸̝͚͍̀̀͐ṁ̵͓̩̎̆̾͘ ̷̥̟̪̒͒͛̚ạ̸̙͇͍̩̈́͋̾̈͒̂n̶̺̬̠͓̟̉̈̾̋̕͝ͅd̵̹͠ ̷͎͈̲̜̝̏͌̀͜t̵̡̼͇̤͖͆̈́̋̈́̿͘h̶̢̥͈̩̦͓̀ò̶̢̹͉̳̗̦̔͒s̸̟̈̑ẹ̶̛̒̓͐͘̚ ̴͇̖͔̙͎͌͗̈́̾̿̿ơ̶͙͗̾̍̉̀f̴͚̘̣̜͖̖͆ ̶̲͈̠̣͗͆̈́̾ţ̷̱̻̍͑h̷̥͕̋͂̐͑̕ȩ̶̖̯͇̓̔͝ ̶̼̻͌̓p̷̞͙͚̣͓̃ë̸͑̋̒̈́͜͝a̵̩͊̊͊̅̀͠ͅs̷͚̹̍͌à̸̡̻̃͠n̴̲̬͕̐͗́̆̓t̴͙̙̻̼̙̓ ̶̧̫̝͓̟͓̔͑̈́͘ṟ̶͕͔͖̋̾͒e̷͔͋͒a̶̧̢̝̤̮̖̒̔̌́͊͝ḽ̴̺̓̒̒͂͘m̶̻̝̰̩̎̓͗š̴̪̮̪͋̆̀̾ ̸̛̪̻ą̸̼̮̟̣̒͛̔r̶̰̱̥̃̆̀͊̆e̶̡̠̜͎̠͒͗̆̔̕͠ ̴̟̐͘f̶̠̥͙́̀̊͂̏͠ǫ̵͉̲̼̭̯̑̓̄͆̿r̵̨̯̙̻̫͎̃̊b̵̠̪̯̓̾̀̽̓i̷̪̺̙̅̓̾̅̑d̵̮͗̓̂̾̀d̷̮͖͓̪̤͕͌͆͐͛̚e̶͙͍͇̓̏̈́̉n̴͕͔̪̣͉̱͆̎̉̂̉̍ ̴̭̺͚̦͚͑͊̂̏̕͠t̷̢͓͗͠ö̷̠͚͇́̉͋͜ ̷̫̿͊̂͊̅u̵̘̦̦̻̬̅̃̈̈ͅs̶̛͙͍̟̞̹̏̄̚͜e̴̺͍̒͌̉̉̿ ̷̖̬͓͕́͊i̷͉͖̯̪̣͛͗͌͐͌͝ţ̵̻̙̖͍̱͌̊̒͝.̶̛͔͌̃̽
̸͍̃̽̀
̶̯̘̪͚̫̊̋̂̾̌͘P̷͇̐͐̔̆l̸͔̼͚̭̰̭̃̌̾̐͝e̶̻̎a̵͇̟͂̚s̸̯͎̙̉ȅ̸͍̞ ̷̛̬̜̟͔̗̈̿͜r̸̻͂̉̆ë̵͖͈͓̮́̂͝p̸̢̮͍̦̠̎̎͘o̷̱͕͖̓̓r̴̖͍͓̱̗̾̔̍͠ţ̷͈̳̺̣̤́̈́̕ ̶̨̡̱͝t̴̜̱͕̔͒̐͋ẖ̷̡͍͕͍̀͂̆͘i̷̗̜̔̀͛š̶͙̟͖̲̣͇͂ ̴͎̖͚̜̥̣̀̄͘i̵̯̹͕̜̯̓̽̃͂͘m̵̧̝͕̞̹̱̑́̈̇̾m̶͇̻̺̮̣̜̐̎̋̐e̷̡̟̰̪̹̒̄̽̔̆d̴̞̺͚̯̎̈́ḯ̶͓̼͕̙̹̒͋ą̸̜̱̻̱̭̋͋̈́͠ṯ̶̣̱͒e̴̩͋̍͑̃l̷̛̟͇̹̋͗y̷̻͉̺̻̦͔͋͆̈͗̈́͛ ̵͇̫̼͉̔t̶̢̮̣͆͝ỏ̵͖̬͔̼͍̐͊̍̔͛͜ ̸̡̨̛̞̣̳̗̓̈̌͠͝h̵̡̠̱̫͒ͅi̵̫͍̭͕̤͋̋̀͘ͅg̸̨̛̜̖̃̏̋͂̚ͅh̴͙͈̐̐͑̂̏̓ė̸̠̓̈̔r̷̞̭̓̓̋̀͝ ̸̡̲̤̓̾̓̈͋͊o̸̖͔͚͉͍̒̓f̸̩͕̽̿f̴̨̮̲͍͛̉̒̑͜͝i̷̻͗͌c̵̗̀̐i̶̛̜͖̙̲͔̣̓̊̈̚͝a̷̡̨̩̺͚̞̎̄̆l̶̼̞̑̐̐̈́̐͊ş̶̞̯̘̙̈̓̀͆͂.̵̬̣̗̱̞̃̓
̴̧̦̼͚̯̤͗
̷̨̡̢͕͇͔̈́̍̏̓͘͝A̵̡̢̛͍̞̼̥̓͑̾̈l̷̞͖̽͆̽͘͝s̸̨͈̫̺̯̯̄̆͂̆̚o̶̧̲̘̒͗̉͘̕̚ ̵̨͙̙͈̳͎͐́̌w̵͉̹̽̐͆ḥ̵̩̯͗͒o̶͇̎͐͋́ ̸̯̺̖̻͗̍t̶̘̤͌f̶͇͙̺͔̑̀̉͌́͠ ̸̛̱̂͑̆̑̕u̸̧̙̦̟͛͘s̶̢̬̪͔̈́͌e̸͈̻̞̤̮̬̾s̸̼̔̒̃̈̿̒ ̵̡̃͛̎̑Ḿ̶̈́̏́̚͜á̴͖͖̈́̔̌̔̈́ċ̶̡̖̼͓̻̯̎O̴͓̣͂̄̈S̸̡̖͇̻̞͐̆̌͛͛ͅ ̸͎̝͕͂i̷̢͍͉̣̙͓̎͒͌n̶̲͙͇̎ ̵̧̢͔̟̠̽͌̓͆̕͜4̵̨̢͇̗̣̈́̌̔̀̑8̵͚̮͇̖̞͆̿̐ͅ2̴̡̺̃̈́̈̈̌͘8̴̡̻͇̀,̵͎̪̇̓̿̍̈ ̶͈̪́̓a̶͔͖͍̦͌̾͜r̶̙͈̿̑͋̈è̸̢̹̠̊ ̵̢͓̫̒̀̾͆͠ỳ̴̙̩̼̾o̸̢͓̞̾̽u̶͍͗͒͒̍ ̷̞̟͎̳̈́́̂̈ͅf̶͈͙̱̰́̃͂̀̿́u̴̡̯͉̖̺͛c̷̻͉̙̹̰̏̏͊̎̿̓k̶̢̗̞̹̗͈̈́i̶̠̊̂̆̐̄n̶̛͔̞͉̹̘̜̋̌͛̿g̵͓̊̌̈́ ̶̨͖̪̦͓̊̅͆̀̈́͊c̸̘͐̈́̕͝r̶̹̈͒̈́͊̄͝ą̴̜̹̭̈́̌̄̅̍ẓ̵̻͎̰͌̂͛͝ỳ̴͎̭͉̫͝ ̶̡̭̻̠̻̉ö̷͔̪̠́̅͐̆͝ͅr̵̗͓͚̫͌͊̄͋̋ ̶̨͙̞̳͕̇͌́̇s̴̘̘̱̘͈̒ͅo̵͚͗̂̃m̴̞̋͜ḛ̶̛̛͍͈̤̄̚ͅt̸̛̪͈̺̯͇͊h̸̨̧͎̯̟̳̅̅̈̈́̐͠i̵̧̯̤̔͝

**Comment by port19x** [comment] 2023-04-29 18:45
Since I still can't reproduce and we'll be working on a similar issue in #1104 I'm closing

**Closed by port19x** 2023-04-29 18:45 UTC
Labels: type: bug, priority 2: medium, status: can't reproduce
