### ISSUE TITLE
"No results found!" on android using termux

### ISSUE THREAD

**Issue by FilipLac** [pystardust/ani-cli#1162] opened 2023-06-28 14:47 UTC
**Metadata (please complete the following information)**
Version Compiled: 4.4.5
Version from pkg: 4.2.0 
OS: Android 13 - Termux v0.118.0
Shell: bash 5.2.15
Anime: any (Sword art online, oshi no ko, onimai)

**Describe the bug**
Tried watching anime, but I'm getting just "No results found!". Downloaded from github and tried even from pkg install. It should've been played in mpv.

**Steps To Reproduce**
1. Install ani-cli on android in termux
2. Run `ani-cli -v oshi`
3. Get "No results found!"

**Expected behavior**
It should show, which episode I want and play in VLC

**Additional context**
Running newest version of Termux, Android and VLC

**Comment by 71zenith** [comment] 2023-06-28 14:49
duplicate of #1161

**Closed by 71zenith** 2023-06-28 14:49 UTC
Labels: type: bug, priority 2: medium
