### ISSUE TITLE
Anime episodes do not appear

### ISSUE THREAD

**Issue by S4MZ171205** [pystardust/ani-cli#1249] opened 2023-12-16 21:16 UTC
**Metadata (please complete the following information)**
Version: 4.7.1
OS: Windows 11
Shell: git bash inside Windows terminal

**Describe the bug**
When choosing an anime, the episodes do not appear.

**Steps To Reproduce**

1. Run `ani-cli -d flcl`
2. Choose 2

**Expected behavior**
Anime episodes should appear

**Comment by Derisis13** [comment] 2023-12-20 08:02
> having the same issue on windows 10

please provide information regarding your shell and ani-cli version

**Comment by Derisis13** [comment] 2023-12-20 08:04
@S4MZ171205 sounds like fzf is not opening. Are you sure you're using the windows terminal and not git bash's one?

**Comment by stunner999** [comment] 2023-12-20 13:41
![3](https://github.com/pystardust/ani-cli/assets/129099102/b40ae91c-3d7e-40a0-93e3-683600588bb3)
![3](https://github.com/pystardust/ani-cli/assets/129099102/00cb94eb-cac4-40bb-89c5-1b0ad1f34740)
then this happens.
![3](https://github.com/pystardust/ani-cli/assets/129099102/01eb8e9b-2863-40b1-aa6b-b3c8a37242f0)

**Comment by S4MZ171205** [comment] 2023-12-20 22:13
> @S4MZ171205 sounds like fzf is not opening. Are you sure you're using the windows terminal and not git bash's one?
I've used gitbash and the same problem occurs

**Comment by S4MZ171205** [comment] 2023-12-20 22:14
> @S4MZ171205 sounds like fzf is not opening. Are you sure you're using the windows terminal and not git bash's one?

I've tried using both and the same problem occurs

**Comment by S4MZ171205** [comment] 2023-12-20 22:17
> > > having the same issue on windows 10
> > 
> > 
> > please provide information regarding your shell and ani-cli version
> 
> ani-cli version 4.7.1 powershell 7.4.0 inside windows terminal
> 
>  231220-192751.webm

This is exactly the same thing that happens

**Comment by Derisis13** [comment] 2023-12-21 08:33
There are a lot of people here, it's getting hard to keep track of who did what, so to level the fields, all of you please do a complete reinstall like written here: https://github.com/pystardust/ani-cli#tier-2-support-windows-ios-steam-deck.
at the end please run `ani-cli -U` to be safe

**Comment by KlonHowWhy** [comment] 2023-12-21 09:12
> There are a lot of people here, it's getting hard to keep track of who did what, so to level the fields, all of you please do a complete reinstall like written here: https://github.com/pystardust/ani-cli#tier-2-support-windows-ios-steam-deck. at the end please run `ani-cli -U` to be safe

Sadly it still doesn't work.
Not running `ani-cli -U` returns a "No result found." after inputting the anime name, that's what happened the first time I installed ani-cli.
After inputting it however, the anime title search works but now the episode choice menu is broken and keeps exiting; same problem as the one they have...

**Comment by Tholleman** [comment] 2023-12-21 19:54
Seems like the issue is that line 205 still uses --cipher even though it was removed in other places. Removing it solved it for me

**Comment by KlonHowWhy** [comment] 2023-12-22 00:37
> Seems like the issue is that line 205 still uses --cipher even though it was removed in other places. Removing it solved it for me

How to do that, may I ask?

Should I remove the whole highlighted part or just the `--cipher` one?
![Screenshot 2023-12-22 093325](https://github.com/pystardust/ani-cli/assets/96662615/066596e2-7480-452d-9f4f-ef37650f996d)

**Comment by KlonHowWhy** [comment] 2023-12-22 00:52
Nevermind, I tested both and found out that I need to remove the whole highlighted part as seen in the screenshot above. Thank you for finding the problem and figuring out the fix! ^^

**Comment by port19x** [comment] 2024-01-05 13:49
Fixed in #1252

**Closed by port19x** 2024-01-05 13:49 UTC
Labels: type: support, os: windows
