### ISSUE TITLE
sudo make not doing anything

### ISSUE THREAD

**Issue by P50ACA** [pystardust/ani-cli#159] opened 2021-12-01 19:43 UTC
Im on manjaro and whenever I cd into "ani-cli" after installing it, and I sudo make, it gives me this error: 
![image](https://user-images.githubusercontent.com/57576932/144302671-7f5f1665-8ed2-4daf-ade2-4c66b6a33a37.png)

**Comment by TheGlockMisc** [comment] 2021-12-01 23:08
Your Distro is Arch Linux right?
If yes, try running:
```
sudo pacman -Syu
```

**Comment by MataevsLinux** [comment] 2021-12-03 02:27
> 

it didn't work for me.

**Comment by shulkk** [comment] 2021-12-04 03:23
try installing [libffi](https://archlinux.org/packages/core/x86_64/libffi/) maybe? ``sudo pacman -S libffi``

**Comment by ura43** [comment] 2021-12-29 12:55
The makefile definitely needs some dependency checking, in its current state it seems almost worse than having no makefile at all. This would also help potential package maintainers i.e. for the AUR

**Comment by Dabbing-Guy** [comment] 2021-12-29 21:00
This issue might be caused by that shared library getting accidentally deleted. You can always try copying some other library and naming it that. 
`sudo cp /usr/lib64/libinput.so /usr/lib64/libffi.so.8`
It **will not** actually fix the underlying issue (that library not existing), but it should allow you to use gcc and make.

**Comment by ura43** [comment] 2021-12-31 14:31
This one is most likely due to that library missing and not at all related to our makefile.
But even if it were, since the makefile will see a great deal of changes, I'll close this issue now.
Open a seperate issue if you still have problems with the makefile

**Closed by ura43** 2021-12-31 14:31 UTC
Labels: type: bug, priority 3: low

**Comment by P50ACA** [comment] 2021-12-31 22:47
[image: image.png]
