### ISSUE TITLE
Cant search animes on tailsos

### ISSUE THREAD

**Issue by HaxSam** [pystardust/ani-cli#344] opened 2022-01-15 14:54 UTC
I'm using tailsos and when I try to search an anime I don't get any results.
I tried with torify and also without.

**Comment by 3ricsonn** [comment] 2022-01-15 16:42
What anime were you looking for, so that we can eventually reproduce the error for debugging

**Comment by HaxSam** [comment] 2022-01-15 16:56
The search don't work
When I try to search neon genesis, neo, attack on titan and so on it always say `No search results found`

**Comment by CoolnsX** [comment] 2022-01-15 17:13
Its due to gogoanime site having bandwidth issues..

**Comment by ura43** [comment] 2022-01-15 17:13
> I'm using tailsos and when I try to search an anime I don't get any results. I tried with torify and also without.

Well, does it work without Tor?
Blocking Tor traffic isn't uncommon

**Comment by HaxSam** [comment] 2022-01-15 17:14
So I tryed to use the search function from the script and see which output I get
I used `torify curl -s https://gogoanime.cm//search.html -G -d "keyword=neo" > index.html`
When I watched the html file I got a recapture request

**Comment by CoolnsX** [comment] 2022-01-15 17:14
I tried it on my browser and it is slow as hell

**Comment by ura43** [comment] 2022-01-15 17:14
> I tried it on my browser and it is slow as hell

Gogo itself?

**Comment by CoolnsX** [comment] 2022-01-15 17:17
> > I tried it on my browser and it is slow as hell
> 
> Gogo itself?

Yup.. even the searching and opening another page is slooooooww

**Comment by HaxSam** [comment] 2022-01-16 16:25
> > I'm using tailsos and when I try to search an anime I don't get any results. I tried with torify and also without.
> 
> Well, does it work without Tor?
> Blocking Tor traffic isn't uncommon

I tried without torify and it also didn't work, but I guess it's possible that tailsos go by default through the Tor network when I don't use torify.

I tried to get to gogo with the Tor browser and that worked

**Comment by ura43** [comment] 2022-01-18 19:49
This could actually be a hint at [reCAPTCHAv3](https://developers.google.com/recaptcha/docs/versions) already being implemented

**Comment by HaxSam** [comment] 2022-01-18 19:52
I don't think its [reCAPTCHAv3](https://developers.google.com/recaptcha/docs/versions) when I opened the response it was from Cloudware

**Comment by ura43** [comment] 2022-01-24 06:53
Please verify that the issue persists when you're not on the tor network

**Comment by ura43** [comment] 2022-01-25 14:45
Closing because the issue is very likely out of our control

**Closed by ura43** 2022-01-25 14:45 UTC
Labels: type: bug, category: url, priority 3: low
