### ISSUE TITLE
ani-cli "Episodes bit released yet!" error

### ISSUE THREAD

**Issue by teelrabbit** [pystardust/ani-cli#958] opened 2022-12-27 17:32 UTC
**Metadata (please complete the following information)**
Version: [e.g. 2.0.2]
OS: [e.g. Windows 10 / Linux Mint 20.3]
Shell: [e.g. zsh, run `readlink /bin/sh` to get your shell]
Anime: [e.g. flcl] (if applicable)

**Describe the bug**
Downloading is broken.
It says something about an unsupported protocol, see screenshot.

**Steps To Reproduce**
- run ani-cli
- search for any anime
- select it 
- choose an episode and click enter
- you should then see the following response 
- "Episodes bit released yet!"

1. Run `ani-cli -d flcl`
![Screen Shot 2022-12-27 at 9 29 49 AM](https://user-images.githubusercontent.com/55339121/209701542-7051fcf3-9496-4fd8-8918-d2246f065f98.png)

2. Choose 2 (fooly-cooly)
3. Choose episode 1

**Expected behavior**
Downloading should work

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/82055622/151030428-2e78d15f-4ba9-4d86-b6f3-8307557b4b29.png)

**Additional context**

**Comment by justchokingaround** [comment] 2022-12-27 17:57
duplicate of #948

**Closed by justchokingaround** 2022-12-27 17:57 UTC
Labels: type: bug, priority 2: medium

**Comment by Elite88-code** [comment] 2026-04-16 15:18
"episode is released but no valid sources" problem in ani-cli. every anime gives this problem.

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/67326eb5-a7f6-4f56-9c6f-0b8c2fb7b50f" />
