### ISSUE TITLE
Won’t work with iSH

### ISSUE THREAD

**Issue by Lockl00p** [pystardust/ani-cli#988] opened 2023-01-25 16:08 UTC
**Metadata (please complete the following information)**
Version: latest
OS: iOS
Shell: ash
Anime: [e.g. flcl] (if applicable)

**Describe the bug**
It won’t even start scraping, as in it tries to search anime then says no results found

**Steps To Reproduce**

1. Install iSH
2. Install ani-click v4
3. Run ani-cli -d [anime]

**Expected behavior**
It should at least find an anime to begin with

**Comment by port19x** [comment] 2023-01-25 16:21
What the heck is iSH

**Comment by Lockl00p** [comment] 2023-01-25 16:27
It’s a Linux container for iOS. [Here](http://ish.app/)

**Comment by Lockl00p** [comment] 2023-01-25 16:49
> What the heck is iSH

Linux container for iOS [Here](http://ish.app/)

**Comment by Terraro53** [comment] 2023-01-25 23:35
I checked it out myself. The issue is the same as this #984 version of wget available in the alpine linux container is old enough to suffer from it.

**Comment by Derisis13** [comment] 2023-01-27 01:38
On termux there's `am start` to launch the apk version of mpv/vlc. Can (and how) we get a graphical player on ish, or is it for downloading only?

**Comment by CoolnsX** [comment] 2023-02-02 17:27
problem is it uses busybox utils for which we tried to make the script compatible but it was always failed.. so it's nearly impossible
Also even if we able to make it compatible with busybox, we still need to get through downloading/streaming since we never used this (And we are not rich plebs).. so it's out of our reach.. :disappointed:

**Comment by port19x** [comment] 2023-02-22 06:32
> problem is it uses busybox utils for which we tried to make the script compatible but it was always failed.. so it's nearly impossible Also even if we able to make it compatible with busybox, we still need to get through downloading/streaming since we never used this (And we are not rich plebs).. so it's out of our reach.. disappointed

Well, the rich plebs among us certainly wouldn't buy apple. I'll close this as, in addition to all that @CoolnsX has said, it's not reasonably maintainable without a dedicated maintainer.

**Closed by port19x** 2023-02-22 06:32 UTC
Labels: type: feature request, os: other, status: needs triage, priority 4: wishlist

**Comment by nightwolf3140** [comment] 2023-04-08 22:08
It would be fun to figure out a iOS solution.

**Comment by nightwolf3140** [comment] 2023-04-08 22:10
@Lockl00p 
I use iSH to ssh to my PC use ani-cli to download a file. Then I use scp to save it locally to my phone and play it with vlc.

**Comment by RubenPonce** [comment] 2023-04-11 21:22
A potential solution to implementing iOS support would be to use the x-callback-url when the shell is iSH. So instead of opening the stream, the ani-cli menu could display a link to open the $episode url stream in MPV and VLC. Or just choose one app. like so: 

 `printf '\e]8;;%s\e\\%s\e]8;;\e\\\n' "vlc-x-callback://x-callback-url/stream?url$episode" "Tap to Play in VLC"`

this allows iSH to generate a link that'll open up the iOS shortcut to VLC and VLC to open the network stream.
I would write this myself but I don't really know how the episode menu selection works.

**Comment by CoolnsX** [comment] 2023-04-11 23:15
> 

Noice...

**Comment by nightwolf3140** [comment] 2023-04-21 04:49
Ok so this is a really stupid way of fixing it, ut heres how I sorted solved it using ssh and a raspberry pi.

```bash
#!/bin/bash

# Define variables for SSH connection and remote file location
remote_host="your_remote_host"
remote_user="your_remote_user"
remote_file_path="path_to_remote_file"
local_dir_path="path_to_local_directory"

# SSH into remote server and execute ani-cli command to select episode and download video
ssh -t $remote_user@$remote_host "ani-cli"

# SCP the downloaded files from remote server to local folder
scp -r $remote_user@$remote_host:$remote_file_path $local_dir_path
```
code generated by chat-gpt (didnt have time) but it works

**Comment by nightwolf3140** [comment] 2023-04-21 05:07
I made a workaround
[](https://github.com/pystardust/ani-cli/issues/1094)

**Comment by Lockl00p** [comment] 2023-04-27 16:44
> A potential solution to implementing iOS support would be to use the x-callback-url when the shell is iSH. So instead of opening the stream, the ani-cli menu could display a link to open the $episode url stream in MPV and VLC. Or just choose one app. like so:
> 
> `printf '\e]8;;%s\e\\%s\e]8;;\e\\\n' "vlc-x-callback://x-callback-url/stream?url=$episode" "Tap to Play in VLC"`
> 
> this allows iSH to generate a link that'll open up the iOS shortcut to VLC and VLC to open the network stream. I would write this myself but I don't really know how the episode menu selection works.

I got it to work, may I make a pull request with some of that code? It was heavily adjusted but still uses OSC-8.

**Comment by nightwolf3140** [comment] 2023-04-27 22:37
Thats awesome!!
