### ISSUE TITLE
ani-cli all anime return 

### ISSUE THREAD

**Issue by FoolsHonor** [pystardust/ani-cli#977] opened 2023-01-16 17:11 UTC
all anime return this error, this used to work for me a while a go then after a year or two rebuilt my pc and now it does not work even fom android, pacman and build from source

Search Anime           
> hack
Query Results >> 
(1) hackgift
(2) hacksign
(3) hackroots
(4) hackquantum
(5) hacksign dub
(6) hackliminality
(7) hackroots dub
(8) hackgu trilogy
(9) hackgu returner
(10) hackliminality dub
(11) hacka doll the animation
(12) hacklegend of the twilight
(13) hackthe movie sekai no mukou ni
(14) hacktasogare no udewa densetsu dub
(15) atasha kawajiri kodama da yo dangerous lifehacker no tadareta seikatsu
(q) quit
> 5
Episodes not released yet!

**Comment by malmerri42** [comment] 2023-01-16 17:44
see #948

**Comment by justchokingaround** [comment] 2023-01-17 05:13
duplicate of #948

**Closed by justchokingaround** 2023-01-17 05:13 UTC
