### ISSUE TITLE
"No results found!" because of Cloudflare (Windows 11)

### ISSUE THREAD

**Issue by MMMNB44** [pystardust/ani-cli#1164] opened 2023-06-28 23:15 UTC
**Metadata (please complete the following information)**
Version: 4.4.0
OS: Windows 11
Shell: Git bash
Anime: All

**Describe the bug**
I get "No results found!" when searching for any anime.

**Screenshots (if applicable; you can just drag the image onto github)**

![image](https://github.com/pystardust/ani-cli/assets/136252519/4523acdc-12dd-43fe-9b22-a446767f8498)

**Additional context**
I opened the code and found this:

![image](https://github.com/pystardust/ani-cli/assets/136252519/bf45b524-fc34-4795-9d83-ee9de42d1649)

So I took this `https://api.${allanime_base}/allanimeapi` link and put it in my browser (replacing the variable with the site's name `allanime.to` of course) which redirected me to this page:

![image](https://github.com/pystardust/ani-cli/assets/136252519/ce6da08e-d5c9-462c-b3dd-eb1c4fe01f3d)

I have seen seemingly the same issue submited by others previously, but didn't find a solution that works for me. But I am also kind of stupid so I might have not understood them?!?

Thanks in advance!

**Comment by Derisis13** [comment] 2023-06-28 23:58
Duplicate of #1161, please discuss there

**Closed by Derisis13** 2023-06-28 23:58 UTC
Labels: type: bug, priority 2: medium
