### ISSUE TITLE
Requests not working

### ISSUE THREAD

**Issue by Nycz-lab** [pystardust/ani-cli#1163] opened 2023-06-28 19:02 UTC
**Metadata (please complete the following information)**
Version: Newest
OS: Linux Mint 20.3
Shell: Bash

**Describe the bug**
AllAnime Base has changed from "allanime.to" to "allanime.day"

**Steps To Reproduce**

1. Run `ani-cli`
2. Search for anything

**Expected behavior**
Search Results pop up

**Comment by Derisis13** [comment] 2023-06-28 23:59
Duplicate of #1164, please discuss there

**Closed by Derisis13** 2023-06-28 23:59 UTC
Labels: type: bug, priority 2: medium

**Comment by port19x** [comment] 2023-06-30 16:13
actually it's being discussed at #1161
