### ISSUE TITLE
Video Player not opening

### ISSUE THREAD

**Issue by Nithish-Surya** [pystardust/ani-cli#1318] opened 2024-04-14 09:12 UTC
## **Make sure you are on the latest version by running `ani-cli -U`**

Version: 4.8.0
OS: Arch LInux KDE
Shell: bash
Anime: naruto

**Describe the bug**
i installed the latest ani-cli via yay in arch linux.

Whenever i play any anime it strucks at this screen 
![Screenshot_20240414_143614](https://github.com/pystardust/ani-cli/assets/80063750/5b022878-48a4-4397-93b6-5b926faea2b6)

**Steps To Reproduce**

1. Run `ani-cli naruto`
2. Choose 21
3. Choose episode 1

**Expected behavior**
MPV or VLC shouldn't start

**Comment by Nithish-Surya** [comment] 2024-04-14 10:54
I tried updating ani-cli but it is not working

**Comment by sinasun** [comment] 2024-04-14 16:06
Try to run mpv (from terminal) and see if gives any error

**Comment by port19x** [comment] 2024-04-14 17:44
Can't reproduce. Naruto Ep 1 plays just fine for me

**Comment by Nithish-Surya** [comment] 2024-04-21 17:07
Anyone help me , my mpv and vlc are playing my local files but unable to play any online videos .I think this due to some error with the mpv

**Comment by DocNITE** [comment] 2024-04-23 20:38
Same problem. I cant run any video with `ani-cli`

**Comment by Vihershunde** [comment] 2024-05-06 13:39
In my case mpv icon just flashes in taskbar then closes

**Comment by port19x** [comment] 2024-05-14 06:57
Can someone make a debug log please?
ani-cli not properly opening a video on linux is unheard of.
`sh -x $(command -v ani-cli) > debug.log`

**Comment by Vihershunde** [comment] 2024-05-14 15:55
Hi, I ran the debug command on Fedora 40 with Nix package manager. I got a brief SELinux popup and the Wayland icon flashed in the taskbar. Here's the debug log:

`  GNU nano 7.2                                                                             debug.log                                                                                        
^[[2K
^[[1;34mChecking dependencies...^[[0m
^[[2K
^[[1;36mSearch anime: ^[[0m^[[A^[[K^[7^[8^[[J
`

As a Linux noob, I'm guessing the issue might be on my end.

**Comment by 71zenith** [comment] 2024-05-15 05:05
> Hi, I ran the debug command on Fedora 40 with Nix package manager. I got a brief SELinux popup and the Wayland icon flashed in the taskbar. Here's the debug log:
> 
> ` GNU nano 7.2 debug.log ^[[2K ^[[1;34mChecking dependencies...^[[0m ^[[2K ^[[1;36mSearch anime: ^[[0m^[[A^[[K^[7^[8^[[J`
> 
> I'm guessing the issue might be on my end because of improper nix config

Can u elaborate more on the popup details also how are u using nix to invoke ani-cli. if possible, try using ani-cli through `nix run nixpkgs#ani-cli`

**Comment by port19x** [comment] 2024-05-15 09:32
Nix on fedora through wayland is an almost maximall brittle setup.
Throw in flatpak and you're there

**Comment by 71zenith** [comment] 2024-05-15 13:18
> Nix on fedora through wayland is an almost maximall brittle setup. Throw in flatpak and you're there

Throw in SELinux as well

**Comment by Aanishp** [comment] 2024-05-24 14:46
Same problem

**Comment by port19x** [comment] 2024-06-03 08:16
I'm closing this to prevent "Same Problem" type comments.
Same symptoms aren't indicative of the same cause, at least not with ani-cli.
Please open a seperate issue, unless it's a full outage (in which case the issue will be pinned).
Perhaps I can add something somewhere to document that

**Closed by port19x** 2024-06-03 08:16 UTC
Labels: type: bug, category: player, priority 2: medium, status: can't reproduce

**Comment by Masrkai** [comment] 2025-04-30 07:55
@port19x  I am using Nixpkgs as i am on NixOS, the issue is not from `ani-cli`. 
I know you got fed up of "I had a similar issue" but the fix for me was as simple as adding the `mpv` package as it wasn't installed


so for any future weird misbehaves from nixpkgs, just know you need mpv package which is not bundled by default in the nixpkgs declaration

**Comment by port19x** [comment] 2025-04-30 12:46
@Masrkai your report is greatly appreciated.
You told me what platform you're on, investigated the issue and even found a fix for it.
That's the ideal bug report.

If you want, you can make a pull request fixing this issue over at the nixpkgs repo and mention me or otherwise link this issue so that I can vouch for the fix.

**Comment by Masrkai** [comment] 2025-05-01 01:36
> [@Masrkai](https://github.com/Masrkai) your report is greatly appreciated. You told me what platform you're on, investigated the issue and even found a fix for it. That's the ideal bug report.
> 
> If you want, you can make a pull request fixing this issue over at the nixpkgs repo and mention me or otherwise link this issue so that I can vouch for the fix.

I will try to experiment on it and fix it mentioning this issue as soon as it's possible  🫡

**Comment by Karthik-Sarvan** [comment] 2025-06-02 16:18
Hey everyone, just dropping this here in case it helps others who are stuck like I was.

I’m using Fedora and had the same issue where ani-cli fetches everything, but when it tries to play a video, mpv just flashes and nothing happens. The terminal shows errors like:

less
Copy code
[ffmpeg/video] libopenh264: Unable to create decoder  
Decoder init failed for libopenh264  
Video: no video  
After a lot of trial and error, here’s what worked for me:

1. Disable hardware decoding in mpv (fixes video not loading):
`nano ~/.config/mpv/mpv.conf`

Add this line:
`hwdec=no`

2. Make sure ffmpeg + codecs are fully installed (Fedora-specific):
`sudo dnf install ffmpeg ffmpeg-libs mpv gstreamer1-libav gstreamer1-plugins-ugly -y`

3. (Optional) Temporarily disable SELinux to check if it's blocking:

`sudo setenforce 0`

**Comment by Derisis13** [comment] 2025-06-02 19:44
> Hey everyone, just dropping this here in case it helps others who are stuck like I was.
> 
> I’m using Fedora and had the same issue where ani-cli fetches everything, but when it tries to play a video, mpv just flashes and nothing happens. The terminal shows errors like:
> 
> `[ffmpeg/video] libopenh264: Unable to create decoder Decoder init failed for libopenh264 Video: no video ` After a lot of trial and error, here’s what worked for me:
> 
>     1. Disable hardware decoding in mpv (fixes video not loading):
>        `nano ~/.config/mpv/mpv.conf`
> 
> 
> Add this line: `hwdec=no`
> 
>     2. Make sure ffmpeg + codecs are fully installed (Fedora-specific):
>        `sudo dnf install ffmpeg ffmpeg-libs mpv gstreamer1-libav gstreamer1-plugins-ugly -y`
> 
>     3. (Optional) Temporarily disable SELinux to check if it's blocking:
> 
> 
> `sudo setenforce 0`

Heyo, did you use the copr or just downloaded the script and ran it? Fedora has a whack where they don't package mpv with youtube-dl(? or whatever makes it be able to play urls), and you have to install the one from flathub or rpmfusion.

If you did indeed install from copr, I want to get to the root of the problem and fix it. It should work out of the box, no additional dependencies beyond the ones declared in the package.

**Comment by amulyasarika** [comment] 2025-06-03 04:44
> > Hey everyone, just dropping this here in case it helps others who are stuck like I was.
> > I’m using Fedora and had the same issue where ani-cli fetches everything, but when it tries to play a video, mpv just flashes and nothing happens. The terminal shows errors like:
> > `[ffmpeg/video] libopenh264: Unable to create decoder Decoder init failed for libopenh264 Video: no video ` After a lot of trial and error, here’s what worked for me:
> > ```
> > 1. Disable hardware decoding in mpv (fixes video not loading):
> >    `nano ~/.config/mpv/mpv.conf`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Add this line: `hwdec=no`
> > ```
> > 2. Make sure ffmpeg + codecs are fully installed (Fedora-specific):
> >    `sudo dnf install ffmpeg ffmpeg-libs mpv gstreamer1-libav gstreamer1-plugins-ugly -y`
> > 
> > 3. (Optional) Temporarily disable SELinux to check if it's blocking:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `sudo setenforce 0`
> 
> Heyo, did you use the copr or just downloaded the script and ran it? Fedora has a whack where they don't package mpv with youtube-dl(? or whatever makes it be able to play urls), and you have to install the one from flathub or rpmfusion.
> 
> If you did indeed install from copr, I want to get to the root of the problem and fix it. It should work out of the box, no additional dependencies beyond the ones declared in the package.

I didn’t go the COPR route — just grabbed the script and ran it. Thought it’d be chill, but yeah... Fedora decided to serve me a "lite" version of mpv without the good stuff. No youtube-dl integration, no proper streaming — basically just vibes 😅

Had to manually pull in `ffmpeg`, `gstreamer1-plugins-ugly`, etc. from RPM Fusion to make it behave like a real media player. Then added `hwdec=no` to `~/.config/mpv/mpv.conf` 'cause video decoding just noped out with some openh264 errors.

Now everything works fine — but yeah, this shouldn’t be necessary.

If COPR handles this cleaner, I’m down to nuke my setup and try again. Happy to test and report — Fedora users shouldn’t have to jump through flaming SELinux hoops to watch anime 😂

**Comment by Derisis13** [comment] 2025-06-03 08:17
I'll also try to reproduce, maybe it is indeed missing some selinux stuff. I have it permanently off, so that'd explain why I never came across this issue
