### ISSUE TITLE
ani-cli cannot find /sbin/players/player_mpv

### ISSUE THREAD

**Issue by EPNero** [pystardust/ani-cli#757] opened 2022-06-14 19:01 UTC
**Metadata (please complete the following information)**
Version: 3.0-1
OS: Arch Linux: 5.18.3-arch1-1
Shell: zsh
Anime: -

**Describe the bug**
Downloading is broken.
It says something about an unsupported protocol, see screenshot.

**Steps To Reproduce**

1. Run `ani-cli ` wiith any flag, or just `ani-cli`
2. Check output on terminal:
> ```/sbin/ani-cli: line 470: /sbin/players/player_mpv: No such file or directory```

**Expected behavior**
ani-cli should be giving me the default message, showing the syntax

**Additional context**
Upon installing the latest update from AUR, ani-cli has stop functioning as intended. Tested on 2 separate devices.
(Same output for ani-cli-git and mpv-git)

mpv works on its own

**Comment by NotAShelf** [comment] 2022-06-14 19:05
seems to be a duplicate of #747

**Comment by EPNero** [comment] 2022-06-14 19:21
> seems to be a duplicate of #751

sorry I forgot to clarify, this is *after* I have followed the installation instructions for V3

as a sidenote, installation does not seem to be updated accordingly for the PKGBUILD, as this was *not* a manual install and just me updating ani-cli with a a `yay -Syu`

**Comment by Fmert24** [comment] 2022-06-14 21:01
ım rolling back to v2.2

**Comment by DaBigBlob** [comment] 2022-06-15 08:00
try this
https://github.com/DaBigBlob/ani-cli

**Comment by DaBigBlob** [comment] 2022-06-15 19:14
@EPNero 
dude wtf was ani-cli doing in /sbin/ ?
you are not meant to touch it

**Closed** 2022-06-17 16:01 UTC
Labels: type: bug, priority 2: medium

**Comment by EPNero** [comment] 2022-06-19 13:15
> @EPNero dude wtf was ani-cli doing in /sbin/ ? you are not meant to touch it

apologies for the late response
I did not touch ani-cli, and I have absolutely no clue why it was in /sbin/ but that is how my installation came to be from AUR
