### ISSUE TITLE
OpenBSD: No results found

### ISSUE THREAD

**Issue by katsifolis** [pystardust/ani-cli#1056] opened 2023-03-12 10:07 UTC
![2023-03-12-120546_828x325_scrot](https://user-images.githubusercontent.com/26058964/224537867-50bcf1ec-83bc-4cd1-8f85-44c6cb19c117.png)
This is the output I get when i try to search for an anime

**Comment by Lop010** [comment] 2023-03-12 10:18
Also having this issue.
![image](https://user-images.githubusercontent.com/98214547/224538334-3c300c28-0058-4dcd-8284-48732a2795e4.png)

**Comment by Rusomati** [comment] 2023-03-12 13:03
Ani-cli isnt working on any operating system at the moment.. see: https://github.com/pystardust/ani-cli/issues/1050

A temporary workaround is using the branch named allanime_gql which worked for me

Downloading this branch is pretty simple you just have to use ``git clone -b allanime_gql https://github.com/pystardust/ani-cli/``

Instead of the normal git clone.

**Comment by 71zenith** [comment] 2023-03-12 14:06
As mentioned by @Rusomati , this is a duplicate of #1050. Closing the issue

**Closed by 71zenith** 2023-03-12 14:06 UTC

**Comment by port19x** [comment] 2023-03-13 08:01
Very based
