### ISSUE TITLE
Episodes Not Released Yet

### ISSUE THREAD

**Issue by Tarzerk** [pystardust/ani-cli#981] opened 2023-01-23 18:42 UTC
Version: 3.4
OS: Mac
Shell: Zsh
Anime: Any

The anime says Episodes Not Released Yet whenever I search for any

Playing videos should work

<img width="1208" alt="Screen Shot 2023-01-23 at 12 41 48 PM" src="https://user-images.githubusercontent.com/52636356/214122747-6ebd263f-217d-473d-bbc9-32b7458204e3.png">

**Comment by Tarzerk** [comment] 2023-01-23 18:42
The change showing on the terminal is just an execution permission change.

**Comment by 71zenith** [comment] 2023-01-23 18:59
duplicate of #948

**Closed by 71zenith** 2023-01-23 18:59 UTC
Labels: type: bug, priority 2: medium
